name: Release to TestFlight

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          echo "/opt/homebrew/bin" >> $GITHUB_PATH
          sudo xcode-select -s /Applications/Xcode.app

      - name: Resolve dependencies
        run: xcodebuild -resolvePackageDependencies -project YourApp.xcodeproj -scheme YourApp

      - name: Setup API Key
        env:
          ASC_KEY_CONTENT: ${{ secrets.ASC_KEY_CONTENT }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
        run: |
          mkdir -p "$HOME/.appstoreconnect/private_keys"
          echo "$ASC_KEY_CONTENT" > "$HOME/.appstoreconnect/private_keys/AuthKey_${ASC_KEY_ID}.p8"

      - name: Unlock Keychain
        run: |
          security unlock-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" ~/Library/Keychains/login.keychain-db
          security set-keychain-settings -t 86400 ~/Library/Keychains/login.keychain-db
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "${{ secrets.KEYCHAIN_PASSWORD }}" ~/Library/Keychains/login.keychain-db > /dev/null 2>&1

      - name: Deploy
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
        run: |
          export APP_STORE_CONNECT_API_KEY_PATH="$HOME/.appstoreconnect/private_keys/AuthKey_${APP_STORE_CONNECT_API_KEY_ID}.p8"
          fastlane beta
